version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173" 
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
